# Generated by Django 2.2 on 2019-05-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachid', models.AutoField(db_column='CoachID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(db_column='GameID', primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='Date', max_length=10)),
                ('homescore', models.IntegerField(db_column='HomeScore')),
                ('visitingscore', models.IntegerField(db_column='VisitingScore')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.AutoField(db_column='PlayerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=40)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=40, null=True)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('seasonid', models.AutoField(db_column='SeasonID', primary_key=True, serialize=False)),
                ('seasonyears', models.CharField(db_column='SeasonYears', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamname', models.CharField(db_column='TeamName', max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('conference', models.CharField(db_column='Conference', max_length=4)),
                ('division', models.CharField(db_column='Division', max_length=9)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('playerseasonid', models.AutoField(db_column='PlayerSeasonID', primary_key=True, serialize=False)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=12)),
                ('playerid', models.ForeignKey(db_column='PlayerID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Player')),
                ('seasonid', models.ForeignKey(db_column='SeasonID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Season')),
            ],
            options={
                'db_table': 'player_season',
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp', models.IntegerField(db_column='SP')),
                ('fgm', models.IntegerField(db_column='FGM')),
                ('fga', models.IntegerField(db_column='FGA')),
                ('tpm', models.IntegerField(db_column='3PM')),
                ('tpa', models.IntegerField(db_column='3PA')),
                ('ftm', models.IntegerField(db_column='FTM')),
                ('fta', models.IntegerField(db_column='FTA')),
                ('orb', models.IntegerField(db_column='ORB')),
                ('drb', models.IntegerField(db_column='DRB')),
                ('ast', models.IntegerField(db_column='AST')),
                ('stl', models.IntegerField(db_column='STL')),
                ('blk', models.IntegerField(db_column='BLK')),
                ('to', models.IntegerField(db_column='TO')),
                ('pf', models.IntegerField(db_column='PF')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Game')),
                ('playerid', models.ForeignKey(db_column='PlayerID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Player')),
                ('playerteam', models.ForeignKey(db_column='PlayerTeam', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Team')),
            ],
            options={
                'db_table': 'player_game_stats',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='hometeam',
            field=models.ForeignKey(db_column='HomeTeam', on_delete=django.db.models.deletion.DO_NOTHING, related_name='home', to='nba.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='seasonid',
            field=models.ForeignKey(db_column='SeasonID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitingteam',
            field=models.ForeignKey(db_column='VisitingTeam', on_delete=django.db.models.deletion.DO_NOTHING, related_name='visiting', to='nba.Team'),
        ),
        migrations.CreateModel(
            name='CoachTeams',
            fields=[
                ('coachteamid', models.AutoField(db_column='CoachTeamID', primary_key=True, serialize=False)),
                ('startdate', models.CharField(db_column='StartDate', max_length=10)),
                ('enddate', models.CharField(db_column='EndDate', max_length=10)),
                ('coachid', models.ForeignKey(db_column='CoachID', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Coach')),
                ('teamname', models.ForeignKey(db_column='TeamName', on_delete=django.db.models.deletion.DO_NOTHING, to='nba.Team')),
            ],
            options={
                'db_table': 'coach_teams',
            },
        ),
    ]
